### ISSUE TITLE
[API] Image Uploading

### ISSUE THREAD

**Issue by SomewhatDamaged** [derpibooru/philomena#102]
**Is your feature request related to a problem? Please describe.**
An API endpoint (perhaps `/api/v1/json/images/new`) that would allow for uploading an image

**Describe the solution you'd like**
Generally, the things I'd deem a requirement of this are mostly already limited by the site: 
3+ tags
a rating tag
image not be a dupe
etc

Make it require an API key to stop bots from flooding the site with images without having a user to blame/block.

Allow uploader to: 
set extra tags
add description
add source

Result should either be an image object (if successful), a 401 if no API key, or some kind of meaningful error JSON (so saying if the hash is taken, url couldn't scrape, etc).

**Comment by SomewhatDamaged** [comment]
Should I set the `fingerprint` to a specific value or allow it to be null? (database currently doesn't complain with a null value)

**Comment by liamwhite** [comment]
Fingerprint should be set to a default value
