### ISSUE TITLE
It's possible to add the same tag twice via batch tagging

### ISSUE THREAD

**Issue by Meow** [derpibooru/philomena#111]
**Describe the bug**
title

**To Reproduce**
1. Batch tag
2. Batch tag the same tag again
3. Enjoy trying to remove the tag

**Expected behavior**
Tag should only be added once

**Screenshots**
n/a, easily reproduceable 

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by liamwhite** [comment]
Can't reproduce, please provide more specific steps
