### ISSUE TITLE
Hidden images appears during navigation

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#116]
**To Reproduce**
1. Search anything
2. Hide random image by clicking on the "eye"
3. Open neighbor image
4. Navigate (next/prev) to the hidden image 
5. See it

**Expected behavior**
Hidden images should be skipped

**Comment by liamwhite** [comment]
Are you sure this isn't just because the index update needed time to propagate?

**Comment by stsyn** [comment]
First time it occurred in image, hidden about a month ago

**Comment by liamwhite** [comment]
Could be out of date. Try reindexing it (recasting your hide).

**Comment by stsyn** [comment]
Not helping, immediately hidden images can be viewed this way as well.

**Comment by liamwhite** [comment]
Does it work after some delay (20-30 seconds)?

**Comment by stsyn** [comment]
No
