### ISSUE TITLE
Missing "Fetch" on upload results in button being blocked

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#117]
**Describe the bug**
If user fails to press "Fetch" after inputting an URL (or presumably if file is invalid, not tested that in prod), then upload will naturally fail. Page will then display an error list due to no file and the Fetch button will be blocked, requiring a page refresh/back (and subsequent loss of input data).

**To Reproduce**
1. Go to New image
2. Enter valid tag set and source
3. Enter a valid URL but don't press Fetch
4. Hit Upload
5. Observe error list from not having fetched a file
6. Observe Fetch button can no longer be interacted with

**Expected behavior**
Fetch button is not blocked on no/invalid image upload.
Alternatively, pressing Upload performs a Fetch if there was no image uploaded or image fetched.

**Comment by Azarmidokht** [comment]
I usually fix this by adding just typing a space anywhere in the fetch bar and then removing it - that unblocks the fetch bar.
