### ISSUE TITLE
Issue with advert redirection

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#125]
**Describe the bug**
Advert 435 is meant to point to https://www.equestriadaily.com/search/label/Artist%20Training%20Ground

However it redirects to https://www.equestriadaily.com/

Does the term "search" get culled?

**Comment by liamwhite** [comment]
![Screenshot from 2020-06-03 12-33-10](https://user-images.githubusercontent.com/9658600/83663146-72ec7d00-a596-11ea-9dbc-8a6d364b9bbd.png)
