### ISSUE TITLE
Aliasing to a bad tag fails without an error

### ISSUE THREAD

**Issue by parasprite** [derpibooru/philomena#137]
1. Alias tag to a tag that doesn't exist, or to itself.
2. Green bar - Tag alias queued

It should throw an error to make it more obvious, since it's super easy to not notice one failed when doing a big tag batch.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/0d359ee81e56caee232d5053f57f67d24ac78f90
