### ISSUE TITLE
Filter keeps getting reset to default when not logged in on Firefox Android.

### ISSUE THREAD

**Issue by AppleDash** [derpibooru/philomena#139]
**Describe the bug**
Filter keeps getting reset to default when not logged in on Firefox Android.

**To Reproduce**
1. Go to derpibooru on Firefox Android.
2. Select the "everything" filter and browse a bit.
3. Come back later the same day. The filter is now set to default again.

**Expected behavior**
The filter should stay on Everything until I clear my cookies or change it myself.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 10 GrapheneOS
 - Browser: Firefox 
 - Version: Various, currently 68.3.0

**Additional context**

I do not clear my cookies and other sites persist data fine.

**Comment by liamwhite** [comment]
It's stored in the session cookie. The session cookie gets reset every time you terminate the session (by closing the browser, for example.)

**Comment by AppleDash** [comment]
Can that be changed?

**Comment by liamwhite** [comment]
The session cannot be made persistent without introducing fixation issues. The cookie used to store the current filter can be made persistent.

**Comment by AppleDash** [comment]
> The session cannot be made persistent without introducing fixation issues. The current filter can be stored in a persistent cookie, though.

Yeah, that was what I was getting at. I was hoping the current filter could be stored in a cookie with longer persistence.
