### ISSUE TITLE
Subscriptions lost during merge

### ISSUE THREAD

**Issue by joeyponi** [derpibooru/philomena#140]
**Describe the bug**
If a user subscribes to an image, and then that image is the "source" in a merge, the user is not automatically subscribed to the "target", basically causing them to loose their subscription during the merge.

While not necessarily a bug, this is contrary to the behavior of Booru-on-Rails, which did carry over subscriptions during a merge.

**To Reproduce**
1. User subscribes to image image XXXXXXX
2. Staff member merges XXXXXXX to YYYYYYY
3. User is not auto-subscribed to YYYYYYY

**Expected behavior**
Users subscribed to a source image should be auto-subscribed to the target image following a merge.

**Additional context**
Initially noticed on production (I subbed to 2374933, but when that got merged to 2374952 I was no logger subbed). Tested and verified on a dev instance.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/ccc788a9dad686cf226c4cb06bf561f695482747
