### ISSUE TITLE
502

### ISSUE THREAD

**Issue by slimepunk** [derpibooru/philomena#141]
i'm a bit of a noob here, but i've done docker-compose build & docker-compose run, and get 502 bad gateway when i go to localhost:8080 in my browser. i've been trying to figure this out on my own for hours but i gave up and decided to ask.

i saw a previous issue about this, and i tried the solution there (which was "sudo sysctl -w vm.max_map_count=262144") and it didn't do anything to help.

i'm not really sure what to do, i've tried so many times to get it working. please don't mind how much of a total noob i am, oops.

**Comment by liamwhite** [comment]
Please provide the console output from the docker-compose terminal

**Comment by slimepunk** [comment]
...right after i posted this it randomly started working wtf
