### ISSUE TITLE
API responses with empty jsons

### ISSUE THREAD

**Issue by blauohrfuchs** [derpibooru/philomena#142]
**Describe the bug**
First of all, i'm only trying to get image links from derpibooru through the API.
As described in the docs I'm using the "/api/v1/json/search/images" path.

The Problem is: simple requests like ?q=twilight sparkle work.
But any other (in the docs marked as allowed) parameter like ?filter_id, ?per_page etc. gets me back an empty json.

Also (maybe for another issue):
![image](https://user-images.githubusercontent.com/36333173/84666168-09b72300-af21-11ea-853e-040244c1e5cb.png)
The default is not 25. It's obviously 15?
![image](https://user-images.githubusercontent.com/36333173/84666317-3a975800-af21-11ea-96fc-e2fc262fed56.png)

**To Reproduce**
Open your browser and try the API requests for yourself.

**Screenshots**
![image](https://user-images.githubusercontent.com/36333173/84665992-ceb4ef80-af20-11ea-8778-ba5dcca09ebe.png)
![image](https://user-images.githubusercontent.com/36333173/84666007-d5436700-af20-11ea-9e72-c87fc55787c4.png)

**Desktop (please complete the following information):**
I think the maybe necessary information is that I'm using the requests library in Python.

**Comment by SomewhatDamaged** [comment]
When constructing URLs with parameters, you separate the parameters with ampersand (&).

The query you want is:
[`https://philomena.derpibooru.org/api/v1/json/search?per_page=20&q=twilight`](https://philomena.derpibooru.org/api/v1/json/search?per_page=20&q=twilight)

**Comment by SomewhatDamaged** [comment]
No probs. If you need help with anything else, feel free to give me a poke on Discord (@Damaged#9999) or [Derpibooru](https://derpibooru.org/profiles/Damaged).
