### ISSUE TITLE
(minor) Aliases are case sensitive, even though they probably shouldn't be

### ISSUE THREAD

**Issue by parasprite** [derpibooru/philomena#148]
That is they'll fail if you happen to capitalize the target, and since they're downcased on creation it makes sense to downcase the target.

I'm assuming this goes for implications too, but I haven't tested it.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/0d359ee81e56caee232d5053f57f67d24ac78f90
