### ISSUE TITLE
Merging BoR image with philomena image (and vice-versa) always fails first time.

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#159]
**Describe the bug**
Images, uploaded before philomena, cannot be merged into post-philomena images from the first try and produce an error. One of the image becomes "merged", but all stats of target remains the same

**To Reproduce**
1. Find a dupe report with described images;
2. Try to merge;
3. See error;
4. Repeated merge works.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/da1e6a145d8fb088a264da105973a7d3c467d2b4
