### ISSUE TITLE
Negative boosting terms do not work

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#161]
**Describe the bug**
Search FAQ contains this line

> A negative value meanwhile reduces the relevance score and deprioritizes the affected term when sorting by relevance, e.g., `pinkie pie^-1 || tara strong`.

However, link leads to `pinkie pie^1 || tara strong`. Changing 1 to the -1 leads to the 5XX error.

**Comment by stsyn** [comment]
Also sf parameter in FAQ links is wrong.

**Comment by liamwhite** [comment]
Negative boosting was removed in Elasticsearch 7. The search guide should be updated.
