### ISSUE TITLE
`https://derpibooru.org/session/new` produces message `You can't access that page.`

### ISSUE THREAD

**Issue by mathieucaroff** [derpibooru/philomena#168]
**Bug description**

Trying to login to a derpibooru account requires connecting to the below url: 

https://derpibooru.org/session/new

but this is not possible and a server redirection 302 to derpibooru.org/ happens.

**To Reproduce**

A1. Go to derpibooru.org on a browser where you aren't logged in
A2. Try to upvote or fave or downvote any image
    - You can't log in and the 302 redirection brings you to derpibooru.org

Or alternatively:

B1. Go to https://derpibooru.org/session/new on a browser where you aren't logged in

**Screenshots**

(site after trying to perform any action which requires to login)

![image](https://user-images.githubusercontent.com/22331339/89111600-0c7dc100-d458-11ea-80b6-360f43cd07db.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, version 2004, build 19041.388
 - Browser - all of: Firefox 78.0.2, Firefox 79.0, Chrome 84.0, Chromium 75.0.37 and Opera 69.0
 - Version (version of derpibooru as of today - 2020-08-02)

**Internet providers**

- I've tried it with two French internet providers (my wifi and my mobile connectivity), as well as three web proxy services
    - I always got the 302 redirect and "You can't access that page." message

**Additional context**

- I was logged out from derpibooru when loading the page a few days ago (3 days ago?) 
  - I believe I was loading the page for the first time of the day
- I have no way to log back in so I could not perform any test while being logged in
- I'm very surprised this issue hasn't been reported yet

++ issue search keywords: login, signin, sign-in, connect

**Comment by mathieucaroff** [comment]
So talking with friends showed that clicking on the "Login" button *did* lead to the correct url: https://derpibooru.org/session**s**/new

and also, that my userstyle actually hid the "Login" button in Firefox.

So I believe the fix would be to either:

- fix the automatic links generated to log-when-voting
- point https://derpibooru.org/session/new to https://derpibooru.org/session**s**/new
- point https://derpibooru.org/session**s**/new to https://derpibooru.org/session/new

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/a81464f189fe3c196e74997d432fa0eeb1a38d0f

**Comment by mathieucaroff** [comment]
I believe that to rule out a whole category of bugs which includes this last one, philomena should consider using https://en.wikipedia.org/wiki/Single_source_of_truth more, though it is usually hard to pass information from the backend to the frontend in a type-checked way. I one way to go about that is using JSON as single source of truth.
