### ISSUE TITLE
Add ability to lock specific tags on a post

### ISSUE THREAD

**Issue by ghost** [derpibooru/philomena#170]
It's nice to be able to lock all the tags on posts, but sometimes it's just a specific tag that's likely to cause problems randomly, obviously locked to everyone but mods. This is done as an alternative to"lock everything" which, while not done that often can be a bit of a sledgehammer of a solution at times.

I know e621 does this with a text box that you throw tags into. I don't know the specifics since it was added after my time but both being able to disallow something from being tagged and disallow something from being _removed_ would be really nice to have. Could be done in the form of `disallowed tag, disallowed other tag, -tag I can't remove` would be straightforward enough.

**Comment by liamwhite** [comment]
Is this on a per-image or per-tag basis?

**Comment by Meow** [comment]
> Is this on a per-image or per-tag basis?

Why not both

**Comment by liamwhite** [comment]
Because that requires twice as much work. I want to know what's actually the most useful to implement.

**Comment by Meow** [comment]
Per image is the impression I'm getting from reading Raptor's original issue text, and it does seem like it would be the most useful to resolve the "tag wars"

**Comment by SomewhatDamaged** [comment]
For it to truly be fit for purpose (of halting tag wars), you'd also need to be able to lock a tag so it _cannot_ be set on the image.

**Comment by parasprite** [comment]
Yes, per image to stop tag wars. To prevent anyone from adding or removing a specific tag to that specific image.
