### ISSUE TITLE
Sometimes comments cannot be searched

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#171]
**Describe the bug**
After reproducing affected comments disappears from comment search for normal users (mods still can see them).
Related: https://desuarchive.org/mlp/thread/35778536/#35778642, https://desuarchive.org/mlp/thread/35778536/#35778729

**To Reproduce**
Possibly steps 1 and 2 can be done in any order.
0. Try to search for desired comments (with "Everything" and in incognito if needed) — see them;
1. Delete desired comments;
2. Delete image with those comments;
3. Restore desired comments;
4. Restore image;
5. Retry search from 0. — will be missed.

DB index issue, can be fixed either by reindexing or deleting/restoring one more time.

**Comment by Sollace** [comment]
What happens if you restore the image before you restore the commens?

**Comment by stsyn** [comment]
> What happens if you restore the image before you restore the commens?

Comments will be visible on the image itself, but will be missing from any search, where they should be (for example, when you search for user comments).

**Comment by stsyn** [comment]
> What happens if you restore the image before you restore the commens?

Comments will be searchable as they should be.

**Comment by Sollace** [comment]
> 
> 
> > What happens if you restore the image before you restore the comments?
> 
> Comments will be searchable as they should be.

As I suspected. Seems like a bad UX design. I would have never made it possible to restore a comment without first restoring the image it was on.

I suppose the easiest approach to fixing this without making too many changes would be to always reindex the comments when restoring an image.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/6670b050a1aa5597774a09ea69f64dee11ba4c3b
