### ISSUE TITLE
Textile strike issue with some languages

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#172]
**Describe the bug**
In certain grammatically fine scenarios in some languages you may have part of the text crossed out.

For example:
`test-test, okay-okay` results in "test-test, okay-okay"
`тест-тест, окей-окей` results in "тест~~тест, окей~~окей"

Expected not crossed out text.

**Comment by HushedFox** [comment]
If you change it to `[==тест-тест, окей-окей==]` (no parse) it will be displayed as normal text

**Comment by stsyn** [comment]
> If you change it to `[==тест-тест, окей-окей==]` (no parse) it will be displayed as normal text

It's not really handy to surround each `-` in cyrillic texts with `[== ==]`

**Comment by Meow** [comment]
Fixed with f91190ce
