### ISSUE TITLE
(minor) Trying to reverse a dupe report with keep source/target will delete the post but not undelete the other

### ISSUE THREAD

**Issue by parasprite** [derpibooru/philomena#175]
To reproduce:
1. Do dupe report on post 1 and post 2
2. Keep target (post 2)
3. Post 1 deleted
4. Go back to same dupe report and keep source (post 1)
5. Post 1 and 2 deleted

Expected behavior:
Assume you want to reverse the dupe and undelete the other post for you, otherwise you have post 1 merged to post 2 and 2 merged to 1.

**Comment by stsyn** [comment]
You need to restore merged image before reversing. Afaik, it worked this way in BoR as well, but it prevented you from reversing if at least one image is deleted.

**Comment by parasprite** [comment]
Of course, it didn't take me long to figure that out but I wouldn't have known if I didn't double check the posts. It's just not very intuitive and there's no case where having 2 images merged to each other is desirable. At the very least BoR behavior is better than this, but it would be nice for it to work a little bit more intelligently.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/aa8da0103f555a7889963e281f6e9119691ed2f6
