### ISSUE TITLE
API Help Plox

### ISSUE THREAD

**Issue by NO-ob** [derpibooru/philomena#177]
How do I do an image search with no tags?

I've been constructing the URL as
https://derpibooru.org/api/v1/json/search/images?q=+ tags + &per_page=10&page=1

But if a user doesn't enter tags nothing is returned from the api, ive been getting around this by replacing blank tags with solo but it probably isn't a good solution lel

**Comment by liamwhite** [comment]
Use a wildcard
https://derpibooru.org/api/v1/json/search/images?q=*

**Comment by NO-ob** [comment]
> Use a wildcard
> https://derpibooru.org/api/v1/json/search/images?q=*

Thankyou
