### ISSUE TITLE
slug:* search field works incorrect

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#179]
1. [`https://derpibooru.org/api/v1/json/search/tags?q=slug:ts`](https://derpibooru.org/api/v1/json/search/tags?q=slug:ts) -> in result `"aliased_tag":"twilight+sparkle"`
2. [`https://derpibooru.org/api/v1/json/search/tags?q=slug:twilight+sparkle`](https://derpibooru.org/api/v1/json/search/tags?q=slug:twilight+sparkle) -> empty result
3. [`https://derpibooru.org/api/v1/json/search/tags?q=name:twilight+sparkle`](https://derpibooru.org/api/v1/json/search/tags?q=name:twilight+sparkle) -> in result `"slug":"twilight+sparkle"`

Second query expected to return value as well

**Comment by SomewhatDamaged** [comment]
You need to URI encode the slug or the server URI decodes the + into a space.

[`https://derpibooru.org/api/v1/json/search/tags?q=slug:twilight%2Bsparkle`](https://derpibooru.org/api/v1/json/search/tags?q=slug:twilight%2Bsparkle) -> expected result

**Comment by stsyn** [comment]
Kinda unexpected and not obvious, but ok, will try. Thanks.

**Comment by stsyn** [comment]
I don't believe that it's intended to work this way. Double escaping is required to search:
[`https://derpibooru.org/api/v1/json/search/tags?q=slug:rose%2B%2528filly%2Bfuntasia%2529`](https://derpibooru.org/api/v1/json/search/tags?q=slug:rose%2B%2528filly%2Bfuntasia%2529)

**Comment by SomewhatDamaged** [comment]
Slugs are intended to be URL strings, which means that yes, they have encoding in them sometimes. You're trying to match that encoding with a string search, but that means you have to encode any special characters that are there.

What use-case do you have for slug-searching anyway? Can't you just use the `id` of the tag?

**Comment by stsyn** [comment]
> What use-case do you have for slug-searching anyway? Can't you just use the id of the tag?
User input, so only names or slugs (can encode names to slugs by myself). Right now I'm switching to use names, and it's seems to be a better approach, yeah.

> Slugs are intended to be URL strings
As I see, they're only used for `/tags/` paths, because escaping of some symbols are different and doesn't match what you see in `/search` (but this is questioning the way slugs being made).
