### ISSUE TITLE
Marking reportables as hidden closes reports with no closing user

### ISSUE THREAD

**Issue by parasprite** [derpibooru/philomena#183]
If you delete an image that was reported without claiming it, it will close the ticket and show N/A instead of the mod.
Anything that closes the ticket for you is affected if it isn't claimed first, so deleted forum posts and such are affected in the same way as well.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/90830d361bd944be6b1401a6998ec7a9ec9da69e
