### ISSUE TITLE
Re-enable notifications of image being merged due to duplication.

### ISSUE THREAD

**Issue by Fleetfoot** [derpibooru/philomena#190]
Back on BoR everyone subscribed to an image would receive a notification when the image got merged with another through the dupe merge system. This notification was useful and informative while also adding to the transparency of moderation action.

If possible, please port this feature to Philomena.

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/11276b2339038048508c93276fe4ae78a21f44ac
