### ISSUE TITLE
Tag changes page randomizes posts that were tagged with batch tagging

### ISSUE THREAD

**Issue by parasprite** [derpibooru/philomena#200]
Basically I'm assuming they're all set to the same timestamp, so every time you refresh the page it'll sort by time and then shuffle the images in some new arbitrary order. There's probably a bigbrain way to fix it but setting a secondary sort to image ID might work to prevent it from randomizing.

**Comment by liamwhite** [comment]
Or just sorting it by id instead of creation date.
