### ISSUE TITLE
Insufficient dnp data on tag-related endpoints

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#205]
https://derpibooru.org/api/v1/json/tags/artist-colon-aer0%2Bzer0
```
"dnp_entries":[{
  "conditions":"I would like to upload any new art myself, although edits are welcome"
}]
```

Expected also _at least_ DNP type and Reason. Tag search endpoint is affected as well.

**Comment by SomewhatDamaged** [comment]
Hrmm. Could make DNP its own endpoint, reflective of `/dnp/#` (and add the DNP ID to `dnp_entries` or could just shovel all the public DNP info into that field.

**Comment by SomewhatDamaged** [comment]
An example of the former is:

![image](https://user-images.githubusercontent.com/6394544/94092864-2be50900-fe5f-11ea-9c51-4eb96a0f787a.png)

**Comment by stsyn** [comment]
> Hrmm. Could make DNP its own endpoint, reflective of `/dnp/#` (and add the DNP ID to `dnp_entries`) or could just shovel all the public DNP info into that field.

I personally prefer having this info in common tag output, because I use tag search for batch tag loading, and having to additionally fetch dnp info I needed... meh

**Comment by SomewhatDamaged** [comment]
I added those changes and did a PR over on philomena-dev.

**Comment by stsyn** [comment]
Nice, thanks!

**Comment by liamwhite** [comment]
https://github.com/philomena-dev/philomena/commit/1a6c3731e02484ce1cdb8de0a8d744b956818c9f
