### ISSUE TITLE
Merging images always leads to the dupe report page

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#220]
While it's possible to resolve dupe report while being on the image, button takes you to the listing. It started about month or two ago, when merging code was changed.

Also please separate displaying of already handled dupes, as is was in BoR.

**Comment by liamwhite** [comment]
It is supposed to go back to the duplicate report page.

The exact same separation logic which was present in the Rails code is in use. It doesn't separate dupes by whether they were resolved, it separates them by whether the current image is the source or the target.
