### ISSUE TITLE
Filter dropdown menu shows incorrect filter name

### ISSUE THREAD

**Issue by HushedFox** [derpibooru/philomena#223]
**Describe the bug**
Filter name in the dropdown menu in upper right corner is showing the wrong filter name for certain filters: filter X is active but filter Y name is shown.

It's the same issue as https://github.com/furbooru/philomena/issues/29 but with a bit different global filters that are bugged for me on Derpibooru.

**To Reproduce**
It's plausible that you need to have any custom filters to get this bug as the incorrect filter name is always one of the custom ones.

1. Go to https://derpibooru.org/filters
2. Click on "Use this filter" for  `Legacy Default` or `Maximum Spoilers`  (or on one of the custom filters when you have more than one, I have 10 different custom filters)
3. Scroll up and look at the filter change dropdown menu
4. See that there is incorrect filter name displayed (for me it's one of my custom filters names.). There is also no ability to select `Default`, `Default 18+` or `Maximum Spoilers`  from this dropdown menu.

**Expected behavior**
The correct filter name should be displayed in the dropdown.

**Comment by parasprite** [comment]
Confirmed, but steps to reproduce are different.

1. Have 5 custom filters
2. Cycle through "use this filter" on all of them
3. Cycle through all the global filters the same way
4. Go back and select the first filter in your custom filters list
5. Mine will show the first filter on 2/3 of them. 

I'm not sure exactly what causes it but it looks like the list overflows after 10 and the current filter is missing so it just selects whatever filter you created first.

**Comment by HushedFox** [comment]
I am constantly experiencing this issue. It's not very convenient that I have to go to filters page every single time I want to change my filters and that I have no idea what filter is currently in use because the name is wrong. It would be nice if this could get fixed...

**Comment by Meow** [comment]
I'll attempt to reproduce it locally and hopefully work out a fix today.
