### ISSUE TITLE
Admin tool for absolute nuking

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#224]
**Is your feature request related to a problem? Please describe.**
Removing an image fully requires access to multiple systems and cannot be accomplished quickly or easily.

**Describe the solution you'd like**
"Destroy" button on an image page should delete every instance of the image on the server, on Cloudflare, and trigger a job to remove it from backups.

**Comment by liamwhite** [comment]
While I appreciate the concerns behind this feature, the point of making really removing images difficult is to protect against worst-case data loss scenarios, and the most immediate concerns relating to retention are solved by pressing the "destroy" as soon as you need to permanently remove content, as this will prevent it from being propagated to backups.

- Allowing the application to purge data from the backups server is a disaster waiting to happen if anything bad happens to the app.
- Allowing the application direct access to Cloudflare to purge images is both beyond the scope of the application in a general deployment (maybe using Varnish purge commands would be fine) and exposes the site to unnecessary risk (if you have domains owned in Cloudflare, for instance, an attacker can perform a full takeover of your domains)
