### ISSUE TITLE
use of arrow keys for pages

### ISSUE THREAD

**Issue by VaasKahnGrim** [derpibooru/philomena#233]
basically use of the arrow keys when dealing with search pages and comic posts. For example if your on a search page and want to go to the next page you could use the right arrow key to go to the next page.

Same with comics posted for going between pages of it.

**Comment by liamwhite** [comment]
There are predefined shortcuts for navigation:

Image Lists
---------------
|Key|Description|
|--|--|
|J | Previous page|
|K | Next page|
|F | Favorite image (image under the mouse pointer)|
|U | Upvote image (image under the mouse pointer)|

Image Pages
------------------
|Key|Description|
|--|--|
|J | Previous image (in global index terms, the image posted after the one you're looking at)|
|K | Next image (image posted before current one)|
|R | Random image|
|S | Open source URL|
|L | Open tags for editing|
|I | Go to index page containing the image being displayed|
|F | Favorite image|
|U | Upvote image|

**Comment by VaasKahnGrim** [comment]
is there a place to change these? for example on derpibooru?

**Comment by liamwhite** [comment]
No, there is not at this time.

**Comment by WingbeatPony** [comment]
I think this is a good thing to keep in mind for the future for the planned enhancements to gallery/comic navigation, in that we may end up having prev/next buttons for galleries visible on image pages directly while not browsing the gallery directly. Having a separate prev/next shortcut (perhaps not arrow keys, but A and D or the like) to address those buttons, to immediately start browsing in the first available gallery without having to switch to the gallery first, could be part of that future enhancement.
