### ISSUE TITLE
Ability to lock specific tags on an image

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#238]
Give staff the ability to lock a tag on a specific image. A staff member with the appropriate role can select whether a tag can never be added to a specific image, or never be removed from a specific image.

Ways how this could work:

1. After a tag is added or removed, staff can tick a checkbox in the Tagging History page to "lock" the tag in in its current state
2. There is a tab in the image moderation tools that lists tags that are locked; if a tag is present in the list, its status (present or not present) cannot be changed until it is removed by someone with the proper rights

A user attempting to add or remove a locked tag should receive an error message informing them their tag change was rejected.  Given the propensity for such changes to be accompanied by other tag violations, it is not necessary that other tag changes go through. Given the afore mentioned propensity for violations, the attempt to change the tag should be logged.

**Comment by TheSmilingPony** [comment]
See https://github.com/derpibooru/philomena/issues/170

**Comment by Nebulon-BFrigateFTW** [comment]
This seems like it would be rather complex (what all would be needed in the database to support this?) and cumbersome (that's gonna be a lot of taggings to mark manually) compared to potential alternatives, like automatically preventing logged-out users, or users in general, from reverting staff tag changes that were made within the last year.
