### ISSUE TITLE
Search parameter "deletion_reason" no longer valid

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#25]
**Describe the bug**
Search parameter "deletion_reason" no longer valid

**To Reproduce**
1. Be a mod
2. Search for 'deletion_reason:*' with +del paramaters
3. Get no results

**Expected behavior**
Search returns results of images that match deletion_reason query as they did in BoR

**Comment by liamwhite** [comment]
fixed by 8128d48e8fa4fb4ab22dd26178944a6d8e0cf224
