### ISSUE TITLE
Revise rate/count limits

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#256]
Revise existing count limits for reports, and rate limits for uploads, comments, posts, and tag updates.

Most of these were set during a high drama (and high abuse) period and no longer need to be as strict. Some are particularly aggravating as hitting them deletes any data in forms _and_ resets the counter.

(ideally there'd be an admin control panel to manage these, including fully locking down these abilities, but that's a matter for another ticket).

**Comment by liamwhite** [comment]
Related: https://github.com/philomena-dev/philomena/issues/85

**Comment by Meow** [comment]
Resolved via philomena-dev/philomena@73cb4f46ccb425e47237de5b00e4f4793d99b097
