### ISSUE TITLE
"Deleted Only" and "Deleted/Merged" search results are identical

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#26]
**Describe the bug**
"Deleted Only" and "Deleted/Merged" search results are identical; Deleted Only includes merged images.

**To Reproduce**
1. Be a mod
2. Do a search with Deleted Only parameter
3. Observe results include Marked Duplicate images

~
**Expected behavior**
Results with "Deleted Only" parameter do not include images marked as duplicate.

**Comment by Meow** [comment]
This is a result if us never having updated the ElasticSearch indexes in production. This feature works as intended in development and new deploys. We plan to update the indexes during a round of database maintenance we will do anyway at some point, that will be when the feature starts working in production.

**Comment by liamwhite** [comment]
Mapping updated, starting reindexing now.

**Comment by liamwhite** [comment]
Indexing crashed due to the presence of a NaN value in a row. I restarted it from the beginning.

**Comment by liamwhite** [comment]
Fixed.
