### ISSUE TITLE
Reverse search is broken

### ISSUE THREAD

**Issue by lunjesse** [derpibooru/philomena#262]
**Describe the bug**
For certain images, reverse search does not work. 

**To Reproduce**
1. Go to https://derpibooru.org/search/reverse
2. Go to https://derpibooru.org/images/2623797
3. Copy this link: https://derpicdn.net/img/view/2021/5/28/2623797.png
4. Paste the link to reverse search

**Expected behavior**
I should see the image 2623797 displayed on the result.

I instead see:
Results
We couldn't find any images matching this in our image database.

This also happens with some other images occasionally, but I do not know the pattern.

**Comment by liamwhite** [comment]
Should be fixed now
