### ISSUE TITLE
"Spurious network error"

### ISSUE THREAD

**Issue by 2008Starfall** [derpibooru/philomena#264]
**Describe the bug**
At the part where the Powershell says "Compiling 596 files", later on I get this error saying
"warning: spurious network error (X tries remaining): failed to mmap. Could not write data: Permission denied; class=Os (2)". And another while the program crashed

**To Reproduce**
1. Go onto your Windows Powershell.
2. First run "docker-compose build" and then "docker-compose up"
3. Wait a little while.
4. Get the error

**Expected behavior**
I expected this to have NO errors as well. I followed basically every part of "readme.md".

**Comment by liamwhite** [comment]
Pretty sure this is a bug in WSL, see if the workaround here resolves your issue https://github.com/philomena-dev/philomena/issues/150

**Comment by liamwhite** [comment]
Assuming this has been solved since there is no feedback, reopen if not
