### ISSUE TITLE
Application unable to start

### ISSUE THREAD

**Issue by kekersdev** [derpibooru/philomena#268]
I'm trying to run the latest version using docker-compose (Ubuntu). 
Building process showed some errors but in the end finished successfully.
`docker-compose up` showed the following error:
```
Starting philomena-master_postgres_1      ... done
Starting philomena-master_redis_1         ... done
Starting philomena-master_elasticsearch_1 ... done
Starting philomena-master_app_1           ... done
Starting philomena-master_web_1           ... done
Attaching to philomena-master_app_1
app_1            | /bin/sh: run-development: Permission denied
philomena-master_app_1 exited with code 126
```

Also after this operation **_philomena-master_postgres_1_**, **_philomena-master_redis_1_** and **_philomena-master_elasticsearch_1_** appear running but not **_philomena-master_app_1_** and **_philomena-master_web_1_**

**Comment by kekersdev** [comment]
Never mind
Tried reinstalling everything from scratch and problem magically disappeared

**Comment by kekersdev** [comment]
No idea what was wrong, the only difference i could remember is the fact that I must've used `sudo` when building the first time

**Comment by Meow** [comment]
ok
