### ISSUE TITLE
Accessing account data through the database

### ISSUE THREAD

**Issue by kekersdev** [derpibooru/philomena#269]
Where users' data is stored? Is it possible to manipulate accounts (e.g. change role or email) by editing the database?

**Comment by Meow** [comment]
```sql
update users set role = 'admin' where id = 123;
update users set email = 'me@example.com' where id = 123;
```
in `psql` (if running in Docker, you must run that in the `<name>_postgres_1` container)

**Comment by kekersdev** [comment]
ERROR:  relation "users" does not exist

**Comment by kekersdev** [comment]
Oh, figured it out
Had to connect to philomena database first

**Comment by kekersdev** [comment]
Thank you for your help
