### ISSUE TITLE
Thumbnailer fails to recompute meta on processed images

### ISSUE THREAD

**Issue by mdashlw** [derpibooru/philomena#281]
Thumbnailer fails to recompute meta after processing/postprocessing is complete, resulting in `image_sha512_hash`, `image_size`, `image_width` and `image_height` always being of the original image. 

Regression of https://github.com/philomena-dev/philomena/pull/166

`Thumbnailer.generate_thumbnails` flow:
1. Download original image file from S3
2. Run processors (generates all the versions)
3. Generate dupe reports
4. **Recompute meta using the original file from step 1**
5. Run post-processors
6. **Recompute meta using the original file from step 1**

The issue is that processors (both `process` or `post_process`) can return `replace_original` change with the new file, which is then uploaded to S3 as `full.{format}` replacing the original file, however `recompute_meta` uses the already downloaded original file. `post_process` also receives the old analysis and the old file.

https://github.com/derpibooru/philomena/blob/2c1bbb0870285261f21f2d969e71d5461d2be83c/lib/philomena/images/thumbnailer.ex#L74

**Comment by liamwhite** [comment]
Added a fix [here](785c0e74cd88a0dcc91079ee29364dfc1f5dfa9a) but waiting to resolve some build system hell to test
