### ISSUE TITLE
kivikakk/cmark-gfm is no longer available

### ISSUE THREAD

**Issue by Octelly** [derpibooru/philomena#284]
This breaks the Cargo build.

**Comment by liamwhite** [comment]
Was fixed upstream by https://github.com/philomena-dev/comrak/commit/02bfb661314bd64c8ae4a215d079e35ddcf7bc4b

**Comment by Octelly** [comment]
Thank you for your quick reply! I'm sick atm so it took me a while to notice. The commit you've linked is months old and I didn't see any new commits in any relevant repositories that I could think of, but I have decided to try again.

The readme says that I should be able to just run the project as it is, aka clone and docker compose without further configuration (at least for testing). I have [recorded (Asciinema link)](https://asciinema.org/a/vFtszsbDwTRrs6vfUIXnFbFL1) myself doing so and you can see that it still fails because
```
app-1            | error: failed to get `comrak` as a dependency of package `philomena v0.3.0 (/srv/philomena/native/philomena)`
app-1            |
app-1            | Caused by:
app-1            |   failed to load source for dependency `comrak`
app-1            |
app-1            | Caused by:
app-1            |   Unable to update https://github.com/philomena-dev/comrak?branch=main#c9c19e20
app-1            |
app-1            | Caused by:
app-1            |   failed to update submodule `vendor/cmark-gfm`
app-1            |
app-1            | Caused by:
app-1            |   failed to fetch submodule `vendor/cmark-gfm` from https://github.com/kivikakk/cmark-gfm.git
```

I am a Rust beginner at best, but it says that it is trying to fetch `cmark-gfm` from `kivikakk/cmark-gfm`, which is 404 (at least that's what I got in my browser).

I'm not super familiar with the exact details of how npm or Cargo works, so perhaps I described the issue poorly last time, but the recording should hopefully provide any missing context this time.

Also, (pretty sure containerisation makes this irrelevant) I'm running it on my desktop Arch PC just for testing for now. I plan on setting it up on my Nix server if it ends up working well.

**Comment by BytewaveMLP** [comment]
This is fixed in https://github.com/philomena-dev/philomena, the Derpi fork just hasn't been updated to the latest version.

**Comment by Octelly** [comment]
@BytewaveMLP oh
my bad... sorry
I wasn't sure which is the "source" Philomena, since I've found several different similar repos and at first accidentally attempted to install a 3 year old outdated one :(
Maybe worth a mention in the readme for people like me?

**Comment by BytewaveMLP** [comment]
All good, it trips me up sometimes as well 😛. To my understanding, this is the source tree mirroring what's actively deployed at https://derpibooru.org, including any Derpi-specific fixes/changes/additions. There's a similar repo for Furbooru at https://github.com/furbooru/philomena which itself is just a fork of this repo.
