### ISSUE TITLE
DA image fetcher doesn't work

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#29]
**Describe the bug**
Fetching images from DA results in an unknown error; the upload page returns with an empty thin orange bar beneath the Fetch input. User must download the image to their machine and upload from there.

**To Reproduce**
1. Go to Upload
2. Put a DA image page URL in the Fetch input field and press Fetch or Upload (https://www.deviantart.com/sallycars/art/trixieday-2019-in-MS-paint-818748636 for example)
3. Observe upload fails with no visible error

**Expected behavior**
Image is fetched and ready to upload / uploaded

**Comment by liamwhite** [comment]
Deviantart is 403ing requests from the scraper IP address. I can conceive of potential solutions (like getting an ipv6 /64 and randomizing the bind address), but ultimately at the end of the day they are the problem

**Comment by Azarmidokht** [comment]
Also, by the most part, this bug has been fixed, but it still can't access the full res of images available for download, likely for the reasons that byte mentioned.

**Comment by Azarmidokht** [comment]
And now the problem resurfaced again - like with tumblr, the fetcher now only can fetch raw image URLS by the most part, although for a few artists, it still works as normal.

**Comment by Jazzepi** [comment]
Seems like this issue should be closed.

**Comment by liamwhite** [comment]
Yes.

**Comment by Azarmidokht** [comment]
And now the problem just returned.
