### ISSUE TITLE
Incomplete Docker config: Redix is not configured

### ISSUE THREAD

**Issue by andreymal** [derpibooru/philomena#3]
After `docker-compose up` the captcha is not working and prints this error:

```
(MatchError) no match of right hand side value: {:error, %Redix.ConnectionError{reason: :closed}}
(philomena) lib/philomena/captcha.ex:104: Philomena.Captcha.create/0
```

After editing `lib/philomena/application.ex` to:

```diff
-{Redix, name: :redix}
+{Redix, name: :redix, host: "redis"}
```

Everything is working fine.

It seems you forgot to add Redix config. By default Redix tries to connect to `localhost:6379`, but in the Docker environment `redis:6379` should be used instead.

---

P.S. Also you should use `&&` instead of `;` inside Dockerfile `CMD` instructions for proper error handling. Without this, there will be a chance that Docker will say "Successfully built" even if some command is failed.

**Comment by liamwhite** [comment]
I can only use podman on my system (Fedora 31) which addresses services exposed in separate containers to localhost on all of them. Hence the config irregularity.
