### ISSUE TITLE
docker-compose up dies on sh: 1: brunch not found

### ISSUE THREAD

**Issue by almafeta** [derpibooru/philomena#31]
When trying to install Philomena on a fresh Ubuntu 18.04.3 server, `docker-compose up` fails with:

```
^[[3m[error] Task #PID<0.594.0> started from PhilomenaWeb.Endpoint terminating
## (stop) :watcher_command_error
    (phoenix) lib/phoenix/endpoint/watcher.ex:29:Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:90: Task.Supervixed.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: %Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "watch"], [cd: "/srv/philomena/assets"]]
^[[0m
> @ watch /srv/philomena/assets
> brunch watch --stdin

sh: 1: brunch: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ watch: `brunch watch --stdin`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-07T02_58_55_535Z-debug.log
```

It repeatedly attempts to rerun `brunch watch --stdin` without any change (save the PID and the log timestamp).

The only line prior in the logs that mentioned brunch was 

```
^[[0m^[[37;40mnpm^[[0m ^[[0m^[[31;40mERR!$[[0m^[[35m^[[0m Command failed: git clone --mirror -q https://github.com/liamwhite/rollup-brunch.git /root/.npm/_cacache/tmp/git-clone-f2b88d93.git
^[[0m^[[37;40mnpm^[[0m ^[[0m^[[31;40mERR!$[[0m^[[35m^[[0m fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-f2b88d93/.git'
```

This was the same error as in https://github.com/nodejs/docker-node/issues/1126, but that was fixed in npm v6.13.6.  Philomena is using v6.13.6, so it's probably not a docker or npm issue.

**Comment by liamwhite** [comment]
It's a permissions error. It would be of great assistance if you could help me squish this because I am unable to reproduce it locally, but others have reported it to me and I am uncertain what the fix should be.

In a shell in the container (that is, run this in the context of `docker exec -it philomena_app_1 bash`), run the following:
```bash
chown -R root:root assets/node_modules
(cd assets && npm install)
```

Then tear down your setup (`docker-compose down`) and recreate it. It should work then.

**Comment by SomewhatDamaged** [comment]
Tested this on a fresh install of ubuntu 18.04.3

Ran into the same problem as reported. The fix worked, but the indexing on the DB was messed up.

You'll need to run: `docker exec -it philomena_app_1 mix reindex_all` to repair them.

After doing that, the site was up and accessible.

**Comment by almafeta** [comment]
The two fixes together in conjunction fixed the issue.  (Well, got me to the 502-ing stage, but that is just an issue of the test VM and not an issue with the dockerfile.)  So the above two are a workaround.

**Comment by liamwhite** [comment]
@almafeta @SomewhatDamaged Would you be able to experiment with replacing [this line](https://github.com/derpibooru/philomena/blob/edc127e46c55f35fc59c27efefa8933430304892/docker/app/run-development#L4) with the following:
```bash
(
cd /srv/philomena/assets
npm install || (chown -R root:root node_modules && npm install)
)
```
to see if it fixes the issue for you? (Use a clean environment.)

**Comment by almafeta** [comment]
@liamwhite Spun up a new VM and applied that change before running `docker-compose build`, went right through the build process without a hitch.

**Comment by liamwhite** [comment]
@almafeta thanks!
