### ISSUE TITLE
Complex filter parser behavior is different for frontend and backend

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#37]
Based on [this](https://derpibooru.org/forums/meta/topics/report-site-bugs-here?post_id=4700684#post_4700684) post, spaces around || and && interpreting different on front-end and back-end complex filter parser. Front requires spaces on the both sides, while back does not (also possibly because of this tsORtiaANDfs takes place), which results in having visible "hidden" images.

**To Reproduce**
1. Switch to this [filter](https://www.derpibooru.org/filters/177931);
2. Use the site.

**Expected behavior**
"Hidden images" should not be visible. Probably, since || and && are reserved, back-end behavior is more correct and front-end requires some fixing. However, in case of literal operands spaces should be required and back-end should be tweaked.

**Comment by liamwhite** [comment]
Nah, the operators to be defined on the backend as requiring surrounding whitespace

**Comment by stsyn** [comment]
Maybe, it doesn't really much matter, which part should be fixed
