### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Pathos14489** [derpibooru/philomena#40]
I installed the latest docker-compose and ran the two commands and when I navigate to localhost:8080 nginx gives a 502 error.

**Comment by joeyponi** [comment]
Can you tell us more about your environment? What OS are you running Docker on?

**Comment by Pathos14489** [comment]
Sorry, I'm just an idiot. It was the `sudo sysctl -w vm.max_map_count=262144` that fixed it. I mistakenly read 

> If you are running Docker on Windows

and decided that that command was for troubleshooting a Windows issue, not a Linux issue. Reread over the entire thing after some research into the log files and realized my mistake. Sorry about that.
