### ISSUE TITLE
New Commissions Not Searchable

### ISSUE THREAD

**Issue by SomewhatDamaged** [derpibooru/philomena#56]
**Describe the bug**
Making a new commission (via `/profiles/:name/commission/new`) and then adding an item to it (via `/profiles/:name/commission/items/new`), doesn't update the `commission_items_count` value.

So, when searching commissions and it filters for [`commission_items_count > 0`](https://github.com/derpibooru/philomena/blob/84ac9d27d7728a0dcf09932947b095996d12096e/lib/philomena_web/controllers/commission_controller.ex#L67), it doesn't show the commission.

**To Reproduce**
1. Go to [https://derpibooru.org/commissions](https://derpibooru.org/commissions)
2. Click on "Create My Listing"
3. Create a listing for yourself.
5. Click "Add An Item"
6. Add an item
7. Go to [https://derpibooru.org/commissions](https://derpibooru.org/commissions)

**Expected behavior**
The listing should be searchable via [https://derpibooru.org/commissions](https://derpibooru.org/commissions)

**Screenshots**
Showing debug from my dev build. This shows there being a `commission_items_count` of 0 despite there being a commission item present.
![image](https://user-images.githubusercontent.com/6394544/77626151-043ce300-6f99-11ea-8b27-e56e60b85b52.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox, Chrome
 - Version Latest release

**Comment by liamwhite** [comment]
Went through and fixed all the old data.
