### ISSUE TITLE
[Feature Request, API] Add timestamps to comments response objects

### ISSUE THREAD

**Issue by pingzing** [derpibooru/philomena#66]
**Is your feature request related to a problem? Please describe.**
I can't display timestamps for comments!

**Describe the solution you'd like**
I'd like an extra field added to the comment response object that contains the time it was posted. Something like `posted_at`. If the data is available, a `last_edited_at` might be nice as well.

**Describe alternatives you've considered**
¯\\\_(ツ)\_/¯

**Additional context**
I'd expect date-times in RFC3339 format, in UTC, like they are elsewhere.

**Comment by liamwhite** [comment]
This is easy enough as a first contribution that I would recommend doing it yourself, if you can.

**Comment by pingzing** [comment]
Fair. PR opened here: https://github.com/derpibooru/philomena/pull/67
