### ISSUE TITLE
NSFW stream flag doesn't exist

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#70]
**Is your feature request related to a problem? Please describe.**
Streams have no NSFW toggle on creation or on edit. Local user settings still lists a NSFW flag for streams.

If the setting exists (for streams set up prior to Philomena), there is no awareness that they might be hidden.

**Describe the solution you'd like**
Streams should have a NSFW flag on creation and edit. Users should see information about the flag existing and their ability to change it in their settings, or the toggle be available in the Stream page itself.

**Comment by liamwhite** [comment]
The flag is automatically set based on the adult setting of the source stream. Would you prefer to set it manually instead?

**Comment by TheSmilingPony** [comment]
Ah, that makes sense. An override might be useful in case an artist switches to drawing NSFW but doesn't change setting (assuming the flag would update on the site's end as well).

Information on that flag being set on the creation confirmation message would be helpful (informs feedback to artists on creating channels for them).

Having the toggle on the Streams page, or the user informed of where to find it, would still be ideal; can split that into a different ticket if preferred.

**Comment by liamwhite** [comment]
The NSFW flag is set every time the stream is fetched (when it goes live or offline), not just on creation. I can add the NSFW flag override to the streams form, but bear in mind without further changes (like, must stay NSFW if already NSFW) it will just be set back again after a few minutes.

**Comment by TheSmilingPony** [comment]
In that case it doesn't seem worth it; if a stream is an issue it can be removed until the owner updates their source stream.
