### ISSUE TITLE
Ad banners are being scaled to max width

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#72]
**Describe the bug**
Ad banners are being scaled in the browser to occupy the max width of 729; this is causing blurring issues for some banners submitted under the max limit.

#imagespns img {
    max-width: 729px;
    **width: 100%;
    height: auto;**
}

**To Reproduce**
1. Upload a banner with fine detail (small font or lines) with a width under 729
2. Observe the banner is scaled to occupy the full space

**Expected behavior**
Ad image isn't scaled but displays in the submitted resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/2158409/78364502-d7528680-75bd-11ea-88aa-cd3dccdfe45f.png)

**Comment by liamwhite** [comment]
Is the fix to remove the bolded CSS here or is it more complicated?

**Comment by TheSmilingPony** [comment]
Only the bolded CSS as far as I'm aware.

**Comment by liamwhite** [comment]
Fixed in 658472f16b415b8cdd1afe7667bb4de60cd47e8d
