### ISSUE TITLE
Animated GIF thumbnails have broken transparency

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#73]
**Describe the bug**
Preview /thumb images for animated GIFs show all previous frames of an animation while being played. See https://derpibooru.org/images/2313259 as an example.

Preview:

![large](https://user-images.githubusercontent.com/2158409/78397337-56ad7d80-75f1-11ea-9557-e6350ec00666.gif)

Full:

![2313259](https://user-images.githubusercontent.com/2158409/78397354-5d3bf500-75f1-11ea-84d3-1dbe41eb6bd9.gif)

**Comment by liamwhite** [comment]
Ref for ffmpeg backport https://wiki.debian.org/SimpleBackportCreation

**Comment by liamwhite** [comment]
[ffmpeg_4_2_2_buster_backports.zip](https://github.com/derpibooru/philomena/files/4453296/ffmpeg_4_2_2_buster_backports.zip)

File list:
* ffmpeg_4.2.2-1~bpo10+1_amd64.deb
* libavcodec58_4.2.2-1~bpo10+1_amd64.deb
* libavfilter7_4.2.2-1~bpo10+1_amd64.deb
* libavformat58_4.2.2-1~bpo10+1_amd64.deb
* libavresample4_4.2.2-1~bpo10+1_amd64.deb
* libavutil56_4.2.2-1~bpo10+1_amd64.deb
* libmysofa1_1.0~dfsg0-2_amd64.deb
* libmysofa-utils_1.0~dfsg0-2_amd64.deb
* libpostproc55_4.2.2-1~bpo10+1_amd64.deb
* libswresample3_4.2.2-1~bpo10+1_amd64.deb
* libswscale5_4.2.2-1~bpo10+1_amd64.deb

**Comment by liamwhite** [comment]
[ffmpeg_4_2_2_dev_buster_backports.zip](https://github.com/derpibooru/philomena/files/4453302/ffmpeg_4_2_2_dev_buster_backports.zip)

File list:
* libavcodec-dev_4.2.2-1~bpo10+1_amd64.deb
* libavdevice58_4.2.2-1~bpo10+1_amd64.deb
* libavdevice58-dbgsym_4.2.2-1~bpo10+1_amd64.deb
* libavdevice-dev_4.2.2-1~bpo10+1_amd64.deb
* libavfilter-dev_4.2.2-1~bpo10+1_amd64.deb
* libavformat-dev_4.2.2-1~bpo10+1_amd64.deb
* libavresample-dev_4.2.2-1~bpo10+1_amd64.deb
* libavutil-dev_4.2.2-1~bpo10+1_amd64.deb
* libmysofa-dev_1.0~dfsg0-2_amd64.deb
* libpostproc-dev_4.2.2-1~bpo10+1_amd64.deb
* libswresample-dev_4.2.2-1~bpo10+1_amd64.deb
* libswscale-dev_4.2.2-1~bpo10+1_amd64.deb

**Comment by liamwhite** [comment]
Tracking upstream bug https://trac.ffmpeg.org/ticket/7902
(comment 7)

**Comment by liamwhite** [comment]
FFmpeg upgraded on philomena with a custom patch:
```c
    if (!s->image && avctx->frame_number && is_image_translucent(avctx, buf, linesize)) {
        gif_crop_translucent(avctx, buf, linesize, &width, &height, &x_start, &y_start);
        honor_transparency = 0;
        disposal = GCE_DISPOSAL_BACKGROUND;
    } else {
```
replaced with
```c
    if (!s->image && is_image_translucent(avctx, buf, linesize)) {
        gif_crop_translucent(avctx, buf, linesize, &width, &height, &x_start, &y_start);
        honor_transparency = 0;
        disposal = GCE_DISPOSAL_BACKGROUND;
    } else {
```

This fixes the issue for new images (old images have to be repaired, and the expiration time may be quite long). Here is a copy of an image pulled from the server:
![large](https://user-images.githubusercontent.com/9658600/80855085-ea339780-8c0b-11ea-8b43-b97730a4c60f.gif)
