### ISSUE TITLE
JPEG optimization is lossy

### ISSUE THREAD

**Issue by liamwhite** [derpibooru/philomena#74]
**Describe the bug**
`-strip -auto-orient` always reencodes the image.
https://github.com/derpibooru/philomena/blob/658472f16b415b8cdd1afe7667bb4de60cd47e8d/lib/philomena/processors/jpeg.ex#L26-L32

**Comment by almafeta** [comment]
The JPEG format is orientation-sensitive, AND the format stores orientation data in exif data, so this can't be fixed directly.  Failing to save on a block boundary also breaks rotation.  More up-to-date JPEG formats exist (`-compress Lossless`), but it adds additional software requirements and browsers don't support them. (Edge, the most significant one that did, recently _removed_ support for lossless JPEG when they switched to a Chromium backend).

Simplest improvement:  add `-quality 100` to the convert command, which has the least tolerance for errors.  Downside:  it adds a lot of filesize and is still lossless.

More exacting solution:  convert jpg to webp.  Lossless rotation, but (1) increases scope and (2) you lose Safari support (Apple owns a competing standard).

Most exacting solution:  convert jpg to webp and have quality-100 jpgs as a backup to continue to support people still on Safari.  Even _more_ scope creep _and_ twice the filecount.

**Comment by liamwhite** [comment]
Alternate solution: by far the vast majority of uploads don't have EXIF rotation data, so only apply rotation data when it exists, otherwise just strip the EXIF tags.
