### ISSUE TITLE
Allow filter sharing

### ISSUE THREAD

**Issue by Meow** [derpibooru/philomena#76]
**Is your feature request related to a problem? Please describe.**
Presently it's impossible to share your filter with someone.

**Describe the solution you'd like**
Make it possible to share filters, e.g. specify which users are allowed access to my personal filter, which would make it possible to share the same filter between two accounts.

Additionally there may be a checkbox to make the filter accessible (public), so that it can be shared with anyone.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Meow** [comment]
Additionally, it may be a nice feature to have filters be exportable/importable. E.G. click "export" - get a .json file in return, click "import" and select a .json file (can be clientside) and configure the filter exactly as exported.

**Comment by liamwhite** [comment]
Wouldn't this be a matter of just re-adding the public checkbox to the filter form

**Comment by Meow** [comment]
Indeed I checked it. It would be nice to be able to retroactively apply that checkbox to existing filters while editing, instead of having to create a brand new filter.

**Comment by liamwhite** [comment]
The point of removing the ability to change it after creation is so that you can't make a public filter then be private.

**Comment by Meow** [comment]
Then maybe make a one-way process of making private filters public? E.G. click "convert to public filter", it would warn you about it being irreversible, and if you confirm the private filter turns public permanently.

**Comment by liamwhite** [comment]
That is high effort to implement a feature that very few will use.

**Comment by Meow** [comment]
Isn't it just a single query to set a single boolean variable to true?

**Comment by liamwhite** [comment]
It requires at minimum an extra route, extra controller, an update query which sets the filter public, and all the appropriate template code to handle it. If you want to implement it feel free.

**Comment by Meow** [comment]
I will when I'm back. Leaving the issue open until then.
