### ISSUE TITLE
Gallery bugs

### ISSUE THREAD

**Issue by Azarmidokht** [derpibooru/philomena#77]
**Describe the bug**

(Error 1) Images within galleries move into random positions every day. [FIXED]
(Error 2) Moving images from one gallery page to another is impossible.
(Error 3) the 'gallery' tab in each image is also sorted randomly, although the positions of the buttons only change whenever a image is added.

**To Reproduce**
1. Go to any gallery
2. Click the 'Rearrange gallery' button
3. See error 2
4. Check the image positions in at least five pages
5. Wait one day and check the image positions again
6. See error 1
7.Check the 'Galleries' tab in any image
8.See error 3

**Expected behavior**

1. The most recently-added images should stay in the first positions in the first page of the gallery unless manually reordered.
2. Images shouldn't move positions within the gallery all on their own
3. The functionality of moving images from one gallery page to another should be active.
4. In the 'Galleries' tab within images, galleries should be sorted from most-recently-used to least-recently used and rearrange positions accordingly instead of being sorted at random.

**Comment by liamwhite** [comment]
Error 1 is already fixed, pending full reindex. (The indexed values are wrong, so the items appear to move based on interactions which reindex them.)
