### ISSUE TITLE
Issues with relevance sorting

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#83]
**Describe the bug**
1) For unknown reason it defined as "sf=_score" — https://derpibooru.org/search?q=ts+%7C%7C+fs+%7C%7C+coco&sf=_score&sd=desc 
2) API search results served in wrong order https://derpibooru.org/api/v1/json/search/images?key=%YOUR_API_KEY_HERE%&q=(ts+%7C%7C+fs+%7C%7C+coco)&sf=_score&sd=desc&page=1 (in my case https://derpibooru.org/images/2139776?sd=desc&sf=_score&q=ts+%7C%7C+fs+%7C%7C+coco is the first one.

**Expected behavior**
1) Reasonable sf parameter name;
2) API search results should be the same, as normal search results.

**Comment by liamwhite** [comment]
1. Sort parameter name is deliberately chosen to [line up with Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-sort.html).
2. Fixed
