### ISSUE TITLE
Failing captcha renders source page within page after failure

### ISSUE THREAD

**Issue by SnowySailor** [derpibooru/philomena#84]
**Describe the bug**
When a user submits a form that requires a captcha (when they're not logged in, for example), failing the captcha will replace the form with the original source page (ends up with page inside a page). See images below.

**To Reproduce**
1. Sign out of any account
2. Go to an image
3. Attempt to change the Source but do not fill out captcha
4. Submit

**Expected behavior**
An error message should appear and the input + buttons should not go away.

**Screenshots**
**Before submitting**
![image](https://user-images.githubusercontent.com/6320753/78956836-940e8100-7ab1-11ea-9042-d1b1f7436c4e.png)

**After submitting**
![image](https://user-images.githubusercontent.com/6320753/78956856-a4266080-7ab1-11ea-983a-60e2739736f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74.0.1

**Comment by liamwhite** [comment]
Intercept the error here and do something with it
https://github.com/derpibooru/philomena/blob/5f9e9d98a69cb560e9e10f938ce112399b611294/assets/js/ujs.js#L51-L62

**Comment by SnowySailor** [comment]
This will probably also happen if the captcha is filled out but incorrect. We can probably catch some of the cases on the client side like if they didn't fill it out but there will need to be a server side component to this fix as well.

**Comment by liamwhite** [comment]
The server side component would need to be rendering text with the appropriate error code (so that the flash stays persisted) and the client side would be having JS reload the outer page to fetch the flash

**Comment by SnowySailor** [comment]
It looks like `captcha_plug.ex` is trying to redirect the user to the same page with the flash error but for some reason it's just replacing the input form with the redirection target page instead of redirecting the browser. Might want to see if this is unique to Firefox.

**Comment by liamwhite** [comment]
The UJS fetchcomplete event for the tags input replaces the entire tag input block with the received HTML page.
https://github.com/derpibooru/philomena/blob/5f9e9d98a69cb560e9e10f938ce112399b611294/assets/js/tagsmisc.js#L38-L54

**Comment by SnowySailor** [comment]
So are you suggesting we check the status code for a 302 and refresh the entire document body with the response if it's a 302 and do what we always do for a 200?

**Comment by liamwhite** [comment]
The server code should render a plain 400, then the client code should reload at top level navigation to fetch the flash.

**Comment by SnowySailor** [comment]
When a captcha fails, the `captcha_plug.ex` does a redirect which returns a 302. We could make it a 400 though.

**Comment by liamwhite** [comment]
Yes, that is what I am suggesting.

**Comment by liamwhite** [comment]
Fixed in #85
