### ISSUE TITLE
Editing Uploader credit always sets IP field to 127.0.0.1

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#97]
**Describe the bug**
Editing the Uploader credit field on an image, even to change from Anonymous to not Anonymous, will set the uploader IP to 127.0.0.1

**To Reproduce**
1. As mod, go to an image
2. Edit uploader from anonymous to named or vice versa
3. Observe uploader IP is overwritten to 127.0.0.1

**Expected behavior**
IP is kept if uploading user has not changed.

**Comment by Meow** [comment]
That is intentional
